name: Compilar Plantilla 2D Pura Estables
on: [workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Clonar versión de Godot
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: '4.3-stable'

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Instalar SCons
        run: pip install scons

      - name: Configurar Compilador MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compilar con SCons (Sin 3D ni Módulos Conflictivos)
        run: |
          scons platform=windows target=template_release disable_3d=yes disable_advanced_gui=yes builtin_msdfgen=no module_msdfgen_enabled=no module_svg_enabled=no optimize=size
