name: Compilar Plantilla 2D Pura Estables
on: [workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Clonar versión estable de Godot
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: '4.3-stable' # Descarga la versión 4.3 fija y sin errores

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Instalar SCons
        run: pip install scons

      - name: Configurar Compilador MSVC
        uses: ilammy/msvc-dev-cmd@v1 # Fuerza a Windows a abrir las herramientas de C++ correctamente

      - name: Compilar con SCons (Sin 3D)
        run: |
          scons platform=windows target=template_release disable_3d=yes disable_advanced_gui=yes optimize=size

      - name: Subir el archivo compilado
        uses: actions/upload-artifact@v4
        with:
          name: plantilla-windows-no3d
          path: bin/*.exe
